apiVersion: 1

policies:
  - orgId: 1
    receiver: SmartCity Alerts
    group_by: ["alertname", "zone", "bin_id"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    routes:
      - receiver: SmartCity Alerts
        matchers:
          - alertname = "BinFullNoCollection"
        group_by: ["bin_id"]
        repeat_interval: 30m

      - receiver: SmartCity Alerts
        matchers:
          - alertname = "ZoneOverload"
        group_by: ["zone"]
        repeat_interval: 30m
